version: "2"
services:

  zookeeper:
    image: debezium/zookeeper:0.5
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka:0.5
    depends_on:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper
    ports:
      - "9092:9092"

  mysql:
    image: debezium/example-mysql:0.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

  connect:
    image: debezium/connect:0.5
    depends_on:
     - zookeeper
     - kafka
     - mysql
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: kafka:9092

  watcher:
    image: debezium/kafka:0.5
    depends_on:
     - zookeeper
     - kafka
     - connect
     - mysql
    environment:
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ADVERTISED_HOST_NAME: kafka
    command: watch-topic -a -k dbserver1.inventory.customers
